%YAML 1.2
---
# Snapcraft Recipe for wimlib
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * Snapcraft.yaml reference
#   https://forum.snapcraft.io/t/snapcraft-yaml-reference/4276
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: wimlib
summary: The open source Windows Imaging (WIM) library
description: |
  wimlib is an open source, cross-platform library for creating, extracting, and modifying Windows Imaging (WIM) archives. WIM is a file archiving format, somewhat comparable to ZIP (and many other file archiving formats); but unlike ZIP, it allows storing various Windows-specific metadata, allows storing multiple "images" in a single archive, automatically deduplicates all file contents, and supports optional solid compression to get a better compression ratio. wimlib and its command-line frontend wimlib-imagex provide a free and cross-platform alternative to Microsoft's WIMGAPI, ImageX, and DISM.

  This snap is NOT official, for any issues regarding the use of this snap please refer to the issue tracker:
  https://github.com/Lin-Buo-Ren/wimlib-snap/issues

version: determined-by-version-script
version-script: ./snap/utilities/set-snap-version.bash

# Reason for classic confinement:
# * Requires raw write access to internal partition's NTFS volumes
confinement: classic
grade: devel
icon: snap/gui/icon.png

apps:
  wimlib-imagex:
    command: bin/classic-launch wimlib-launch wimlib-imagex
  wimappend:
    command: bin/classic-launch wimlib-launch wimappend
  wimapply:
    command: bin/classic-launch wimlib-launch wimapply
  wimcapture:
    command: bin/classic-launch wimlib-launch wimcapture
  wimdelete:
    command: bin/classic-launch wimlib-launch wimdelete
  wimexport:
    command: bin/classic-launch wimlib-launch wimexport
  wimextract:
    command: bin/classic-launch wimlib-launch wimextract
  wimdir:
    command: bin/classic-launch wimlib-launch wimdir
  wiminfo:
    command: bin/classic-launch wimlib-launch wiminfo
  wimjoin:
    command: bin/classic-launch wimlib-launch wimjoin
  wimmount:
    command: bin/classic-launch wimlib-launch wimmount
  wimmountrw:
    command: bin/classic-launch wimlib-launch wimmountrw
  wimoptimize:
    command: bin/classic-launch wimlib-launch wimoptimize
  wimsplit:
    command: bin/classic-launch wimlib-launch wimsplit
  wimunmount:
    command: bin/classic-launch wimlib-launch wimunmount
  wimverify:
    command: bin/classic-launch wimlib-launch wimverify
parts:
  # Assets from the snap packaging, refer each READMEs under the `snap` folder for more information
  assets:
    plugin: nil

    override-pull: |
      set \
        -o errexit \
        -o nounset

      # Clear all files in source tree
      rm \
        --force \
        --recursive \
        --verbose \
        * \
        .* \
        || true # Allow no files found

      cp \
        --recursive \
        --verbose \
        ../../../snap/* \
        .

    override-build: |
      set \
        -o errexit \
        -o nounset

      ./utilities/install-assets.bash
    prime:
    - -utilities
    - -patches

  ntfs-3g:
    # edge branch - BLEEDING EDGE!
    #source: git://git.code.sf.net/p/ntfs-3g/ntfs-3g
    #source-depth: 1

    # latest stable version
    source: git://git.code.sf.net/p/ntfs-3g/ntfs-3g
    source-depth: 1
    source-tag: 2017.3.23

    plugin: autotools

  wimlib:
    source: git://wimlib.net/wimlib
    source-depth: 100

    build-packages:
    - libfuse-dev
    - libxml2-dev
    # Replaced by ntfs-3g part
    #- ntfs-3g-dev
    - pkg-config
    stage-packages:
    - libicu55
    - libxml2
    # Replaced by ntfs-3g part
    #- ntfs-3g

    plugin: autotools
    override-build: |
      set -eu

      ./bootstrap

      snapcraftctl build

    filesets:
      copyright:
      - usr/share/doc/*/copyright
      executables:
      - bin/wim*
      executables-others:
      - bin/*
      - sbin/*
      - usr/bin/*
      - -$executables-wimlib
      etc:
      - etc
      library-headers:
      - include
      library-static:
      - lib/*.a
      library-libtool:
      - lib/*.la
      library-shared:
      - lib/*.so*
      - lib/*/*.so*
      - usr/lib/*/*.so*
      manpages:
      - share/man
      manpages-others:
      - usr/share/man
      pkg-config:
      - lib/pkgconfig

    stage:
    - $copyright
    - $executables
    - $library-shared
    - $manpages

    prime:
    - $copyright
    - $executables
    - $library-shared
    - $manpages
